### ISSUE TITLE
Cannot debug on windows

### ISSUE THREAD

**Issue by AlexFsmn** [kevcunnane/sqlops-debug#6]
Version 1.0.2 (Currently latest)
Platform: Windows
Node Version: 8.9.4

Pressing F5 to debug displays the following:
`{ errorCode: 'load',
  moduleId: 'iconv-lite',
  neededBy: [ 'vs/base/node/encoding', 'vs/code/node/cli' ],
  detail: 
   { Error: Cannot find module 'iconv-lite'
       at Function.Module._resolveFilename (module.js:470:15)
       at Function.Module._load (module.js:418:25)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at NodeScriptLoader.load (E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:735:39)
       at OnlyOnceScriptLoader.load (E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:581:32)
       at loadNextPath (E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:1429:41)
       at Object.errorback (E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:1437:25)
       at OnlyOnceScriptLoader.triggerErrorback (E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:594:36)
       at E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:581:151 code: 'MODULE_NOT_FOUND' } }
{ errorCode: 'load',
  moduleId: 'minimist',
  neededBy: [ 'vs/platform/environment/node/argv' ],
  detail: 
   { Error: Cannot find module 'minimist'
       at Function.Module._resolveFilename (module.js:470:15)
       at Function.Module._load (module.js:418:25)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at NodeScriptLoader.load (E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:735:39)
       at OnlyOnceScriptLoader.load (E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:581:32)
       at loadNextPath (E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:1429:41)
       at Object.errorback (E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:1437:25)
       at OnlyOnceScriptLoader.triggerErrorback (E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:594:36)
       at E:\Program Files\SQL Operations Studio\resources\app\out\vs\loader.js:581:151 code: 'MODULE_NOT_FOUND' } }
`

**Comment by kevcunnane** [comment]
Hi Alex, sorry you're having this trouble. You're trying to debug an extension, correct? What is the output of the debug console in the VSCode window you launched SQL Ops from?

**Comment by AlexFsmn** [comment]
Yes, I followed the instructions here:
https://github.com/kevcunnane/sqlops-debug/blob/master/README.md

From debug console:
`E:\Program Files\SQL Operations Studio\bin\sqlops.cmd --debugBrkPluginHost=30190 --debugId=e6eccd76-9039-43c2-ac8d-e5012aa3273a --extensionDevelopmentPath=E:\Path\To\Extension`

After that I get a connection timeout error message.

I also checked the developer console of VSCode but it doesn't give any information.

It seems like some kind of process of sql operations studio was started since I get this error message when trying to start sqlops after trying to debug:
![image](https://user-images.githubusercontent.com/11557675/44955115-2bf7c200-aeae-11e8-8212-5ff25c14c800.png)

Im am running VS Code 1.26.1

**Comment by AlexFsmn** [comment]
It seems like I forgot to run the command `npm install`.
I haven't used Yeoman enough to know if this is necessary. However, it should be added to the documentation if it's missing.
